### PR TITLE
add additional requirements needed to successfully make websites

### PR DESCRIPTION
**Pull request by najuzilu**
These are the additional requirements needed to run `make website` successfully.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @najuzilu this is for this set of lectures only right?

**Comment by najuzilu** [comment]
Yes, but I'll make the PRs for the other two repos today once I build their separate environments. Sounds like a good plan?

**Comment by mmcky** [comment]
great - thanks @najuzilu. I am maintaining an `environment.yml` file which is used by conda I may merge the requirements into that file to keep a single environment file. Is that ok?

The `environment.yml` file will be added in PR #36

**Comment by najuzilu** [comment]
That sounds great! What should I do for the other two repos? Should I wait until we have a `environment.yml` file for each?

**Comment by mmcky** [comment]
it would be great if you made `requirements.txt` and I will migrate.

**Comment by najuzilu** [comment]
I'm getting module not found for `numba.types.containers`  and `numba.targets.linalg`. Any suggestions on how to fix this @mmcky?

**Comment by mmcky** [comment]
now that PR #36 can you please check if any of these are missing from `environment.yml`. Thanks @najuzilu

**Pull request closed without merging**
